### ISSUE TITLE
NoSuchMethodError: TagContainer.clear()

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/CottonScripting#3]
`java.lang.NoSuchMethodError: net.minecraft.class_3503.method_15195()V `

`TagContainer.clear()` got removed at some point, probably 1.14.3. I'm gonna need to redo the tag stuff to make cotton scripting work on new versions.

**Comment by Pannoniae** [comment]
In theory I've fixed it. (replaced it with an accessor + idMap.clear()) Not sure if it works tho (it launches in dev/prod, but not sure if I didn't break anything)

**Comment by Frontrider** [comment]
#4 should fix it.

**Comment by sylv256** [comment]
How do you reproduce this?

**Comment by LemmaEOF** [comment]
This doesn't happen anymore, since Mojang changed tag stuff again.
