### ISSUE TITLE
Scripts Don't Load At First

### ISSUE THREAD

**Issue by sylv256** [CottonMC/CottonScripting#6]
**Describe the bug**
When you first load a world with multiple scripts in it, it won't load all of the scripts. However, after you type `/reload`, all of the scripts will load.

**To Reproduce**
1. Load a world that has a datapack with scripts in it.
2. Look at the available scripts by typing `/script `.

**Versions:**
 - `Cotton Scripting`: `2.0.0-pre.1+1.15.2`
 - `Fabric API`: `0.11.1+build.312-1.15`
 - `Minecraft`: `1.15.2`

**Comment by LemmaEOF** [comment]
oh boy. I'll take a look when I can.

**Comment by sylv256** [comment]
Not sure why, but it doesn't appear to be happening anymore.

**Comment by sylv256** [comment]
I'm going to temporarily close this issue until I figure out how to reproduce it.
